name: Build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - run: echo "Updating..."
    - run: |
           ./build.sh
           git config --global user.email "bot@cc2bots.cf"
           git config --global user.name "AutoUpdateBotFriend"
           git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
           git pull github ${GITHUB_REF} --ff-only
           git add .
           git commit -m "Scheduled Update"
           git push github HEAD:${GITHUB_REF}
